name: "Python pylint"
description: "Ensure Python code quality. Supports pylint, black, mypy and isort."
branding:
  icon: "sun"
  color: "red"
inputs:
  source:
    description: "Source file or directory"
    required: false
    default: "."
  strict:
    description: "Set strictness for lint [low, medium, high]"
    required: false
    default: "medium"
  pylint-options:
    description: "Pylint options"
    required: false
    default: ""
  isort-options:
    description: "Isort options"
    required: false
    default: ""
  django:
    description: "Confirm if source is a Django project"
    required: false
    default: false

runs:
  using: "Docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.source }}
    - ${{ inputs.strict }}
    - ${{ inputs.pylint-options }}
    - ${{ inputs.isort-options }}
    - ${{ inputs.django }}
